recipe-card-push
cse110-fa21-group34/rocketrecipes pull request #45
Opened 2021-11-15 20:44 UTC by Cryszzz

I have made a recipe card as well as an expanded version. (same as Lab 7 of how to use it)
BE CAREFUL: incompatible with JSON file in our repo.

2021-11-17 01:42 UTC, PatrickBrown1 commented
Looks really good so far!

I went through and fixed all of the styling errors so it's passing the tests, however, we aren't completely done. 

Now that we have the recipe schema (in ```./root/models/recipes.json``` ), can you go through and change the util functions (now in ```./root/scripts/RecipeCardUtil.js```) to work with the new recipe schema?

2021-11-17 01:43 UTC, PatrickBrown1 requested changes
See above comment

2021-11-17 02:09 UTC, PatrickBrown1 requested changes

2021-11-17 02:09 UTC, PatrickBrown1 commented on root/component/RecipeCard.js
> +    const ratingVal = searchForKey(data, 'ratingValue');
We don't have a rating for each recipe, so we don't need this part

2021-11-18 21:52 UTC, PatrickBrown1 commented
Fixed recipe card component to work with recipe data, fixed styles so that it follows figma, removed unneeded components.

![image](https://user-images.githubusercontent.com/29768212/142502760-3ef58ecd-3b21-474a-ad7f-3e992db8fc2a.png)

2021-11-18 21:54 UTC, gmihir approved these changes

2021-11-18 21:54 UTC, PatrickBrown1 approved these changes

2021-11-18 21:54 UTC, merged